---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chaimfn--{{.Values.image.name}}"
  namespace: "default"
  labels:
    app: "chaimfn--{{.Values.image.name}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "chaimfn--{{.Values.image.name}}"
  template:
    metadata:
      labels:
        app: "chaimfn--{{.Values.image.name}}"
    spec:
      containers:
      - name: "{{.Values.image.name}}"
        image: "{{.Values.image.repository}}{{.Values.image.name}}:{{.Values.image.tag}}"
        env:
        - name: "PORT"
          value: 3000
        volumeMounts:
        - name: "chaimfn--{{.Values.image.name}}-volume-todofile"
          mountPath: "/app/src/db/todo.json"
      volumes:
      - name: "chaimfn--{{.Values.image.name}}-volume-todofile"
        configMap:
          name: "chaimfn--{{.Values.image.name}}-configmap-todofile"
          items:
          - key: "todo.json"
            path: "keys"
    