---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "chaimfn--{{.Values.image.name}}--service"
  namespace: "default"
  labels:
    app: "chaimfn--{{.Values.image.name}}"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: {{.Values.env.port}}
  selector:
    app: "chaimfn--{{.Values.image.name}}"
  type: "LoadBalancer"
    